include ./theme.conf
cursor none
mouse_hide_wait 1.0
term xterm-256color

copy_on_select yes

strip_trailing_spaces smart

default_pointer_shape arrow
enabled_layouts splits,stack
tab_bar_edge top
tab_bar_style slant
tab_title_template "{fmt.fg.red}{bell_symbol}{activity_symbol}{fmt.fg.tab}{title}"
# tab_title_template "{fmt.fg.tab}{title}"


editor vim
allow_remote_control socket
listen_on unix:${HOME}/.kitty

font_family MesloLGS NF
# font_family  Iosevka Custom Extended
# bold_font  Iosevka Custom Extrabold Extended
# italic_font      Iosevka Custom Extended Oblique
# bold_italic_font Iosevka Custom Extrabold Extended Oblique
font_size 7

clear_all_shortcuts yes
action_alias launch_cwd launch --cwd=current

map cmd+f show_scrollback
map cmd+; next_layout
map cmd+q close_tab
map cmd+t new_tab

map cmd+c copy_to_clipboard
map cmd+v paste_from_clipboard
map cmd+shift+v paste_from_selection

map cmd+equal change_font_size all +2.0
map cmd+minus change_font_size all -2.0

# map cmd+plus change_font_size
# map cmd+r

# map ctrl+k kitten mykitten.py
kitty_mod opt+shift
map kitty_mod+escape>q kitten mykitten.py

# WINDOWS
map kitty_mod+w>n>k combine : launch_cwd --location=hsplit : move_window up
map kitty_mod+w>n>j launch_cwd --location=hsplit
map kitty_mod+w>n>h combine : launch_cwd --location=vsplit : move_window left
map kitty_mod+w>n>l launch_cwd --location=vsplit

map kitty_mod+w>shift+k move_window up
map kitty_mod+w>shift+j move_window down
map kitty_mod+w>shift+h move_window left
map kitty_mod+w>shift+l move_window right

map kitty_mod+w>k neighboring_window up
map kitty_mod+w>j neighboring_window down
map kitty_mod+w>h neighboring_window left
map kitty_mod+w>l neighboring_window right

map kitty_mod+w>d close_window
map kitty_mod+w>n>n new_window
map kitty_mod+w>shift+d close_other_windows_in_tab
map kitty_mod+w>s swap_with_window
map kitty_mod+w>r start_resizing_window
map kitty_mod+w>. focus_visible_window

map kitty_mod+w>1 first_window
map kitty_mod+w>2 second_window
map kitty_mod+w>3 third_window
map kitty_mod+w>4 fourth_window
map kitty_mod+w>5 fifth_window
map kitty_mod+w>6 sixth_window
map kitty_mod+w>7 seventh_window
map kitty_mod+w>8 eighth_window
map kitty_mod+w>9 ninth_window

# TABS
map kitty_mod+tab>n new_tab_with_cwd
map kitty_mod+tab>d close_tab
map kitty_mod+tab>h previous_tab
map kitty_mod+tab>l next_tab
map kitty_mod+tab>. select_tab

# KITTY
map kitty_mod+k>s kitty_shell
map kitty_mod+k>c debug_config
map kitty_mod+k>r load_config_file

# map kitty_mod+j kitten libs/vim-kitty-navigator/pass_keys.py neighboring_window bottom cmd+j
# map kitty_mod+k kitten libs/vim-kitty-navigator/pass_keys.py neighboring_window top    cmd+k
# map kitty_mod+h kitten libs/vim-kitty-navigator/pass_keys.py neighboring_window left   cmd+h
# map kitty_mod+l kitten libs/vim-kitty-navigator/pass_keys.py neighboring_window right  cmd+l

# map ctrl+/ launch --allow-remote-control kitty +kitten libs/kitty-kitten-search/search.py @active-kitty-window-id

# map ctrl+/ no_op
